name: terraform-docs-gh-actions
on:
  push:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - name: checkout project
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Render terraform docs inside the README.md and push changes back to branch
      uses: terraform-docs/gh-actions@v0.11.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
